service: hmap-server
frameworkVersion: '3'

custom:
  tableName: 'options-table'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource:
            - Fn::GetAtt: [ OptionsTable, Arn ]
  environment:
    OPTIONS_TABLE: ${self:custom.tableName}
    TRADIER_KEY: ${ssm:tradier-api-key}

functions:
  api:  
    handler: index.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    OptionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: ticker
            AttributeType: S
        KeySchema:
          - AttributeName: ticker
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
